name: test windows mingw

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_windows_mingw:
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log software version
      run: |
        cmake --version
        gcc --version

    - name: Configure CMake
      run: |
        cmake -S src -B build -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build Project
      run: |
        cmake --build build

    - name: Run Tests
      run: |
        ctest --test-dir build
